spring:
  application:
    name: portalasig-config-server
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: git@github.com:portalasig-microservices/portalasig-config-repo.git
          search-paths: services
          clone-on-start: true
          default-label: ms

server.port: 5859
encrypt:
  key: ${PORTALASIG_CLOUD_CONFIG_KEY}
